import { useEffect, useState } from 'react';
import { api } from './api';
import { optional, value } from './forms';
import { useTask } from './useTask';
import { ErrorState, Field, Loading } from './ui';

type Application = { id: string; version: number; job_id: string; job_title: string | null; company_name: string | null; status: string; submission: { submitted_at: string; channel: string; receipt_ref: string } | null; events: { id: string; to_status: string; at: string; note: string }[] };
const labels: Record<string, string> = { SHORTLISTED: 'Na shortlist', RESEARCHED: 'Pesquisada', SUBMITTED: 'Enviada manualmente', INTERVIEWING: 'Em entrevista', OFFERED: 'Oferta recebida', REJECTED: 'Rejeitada', WITHDRAWN: 'Retirada', EXPIRED: 'Expirada' };
const transitions: Record<string, string[]> = { SHORTLISTED: ['RESEARCHED', 'SUBMITTED', 'WITHDRAWN', 'EXPIRED'], RESEARCHED: ['SUBMITTED', 'WITHDRAWN', 'EXPIRED'], SUBMITTED: ['INTERVIEWING', 'OFFERED', 'REJECTED', 'WITHDRAWN'], INTERVIEWING: ['OFFERED', 'REJECTED', 'WITHDRAWN'], OFFERED: [], REJECTED: [], WITHDRAWN: [], EXPIRED: [] };

export default function Tracker() {
  const [data, setData] = useState<{ items: Application[]; total: number } | null>(null); const [error, setError] = useState(''); const [refresh, setRefresh] = useState(0); const [offset, setOffset] = useState(0);
  useEffect(() => { let active = true; api<{ items: Application[]; total: number }>(`/applications?limit=20&offset=${offset}`).then((value) => { if (active) { setData(value); setError(''); } }).catch((reason: Error) => { if (active) setError(reason.message); }); return () => { active = false; }; }, [refresh, offset]);
  return <><p className="eyebrow">ACOMPANHAMENTO</p><h1>Suas candidaturas</h1><p>Registre o que aconteceu e mantenha um histórico. O envio é feito por você, fora da aplicação.</p>{error ? <ErrorState error={error} retry={() => setRefresh(refresh + 1)} /> : !data ? <Loading /> : <>{!data.items.length && <section className="empty"><h2>Sua shortlist está vazia</h2><p>Adicione uma oportunidade a partir do resultado da análise.</p><a href="#inbox">Explorar Inbox →</a></section>}{data.items.map((item) => <ApplicationCard key={`${item.id}/${item.version}`} item={item} changed={() => setRefresh(refresh + 1)} />)}<div className="actions"><button disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 20))}>Anterior</button><button disabled={offset + 20 >= data.total} onClick={() => setOffset(offset + 20)}>Próxima</button></div></>}</>;
}
function ApplicationCard({ item, changed }: { item: Application; changed: () => void }) {
  const [target, setTarget] = useState(transitions[item.status]?.[0] ?? ''); const task = useTask();
  return <article className="panel"><span className="tag">{labels[item.status]}</span><h2><a href={`#job/${item.job_id}`}>{item.job_title || 'Oportunidade sem título'}</a></h2><p>{item.company_name || 'Empresa não informada'}</p><details><summary>Linha do tempo ({item.events.length} eventos)</summary><ol className="timeline">{item.events.map((event) => <li key={event.id}><strong>{labels[event.to_status]}</strong><p>{new Date(event.at).toLocaleString('pt-PT')}</p>{event.note && <p>{event.note}</p>}</li>)}</ol>{item.submission && <p>Envio registrado: {new Date(item.submission.submitted_at).toLocaleString('pt-PT')} · {item.submission.channel} · {item.submission.receipt_ref}</p>}</details>
    {target && <details className="transition-form"><summary>Registrar atualização</summary><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void task.run(async () => { await api(`/applications/${item.id}/events`, 'POST', { expected_version: item.version, to_status: target, note: value(data, 'note'), manual_confirmation: data.has('manual_confirmation'), submitted_at: optional(data, 'submitted_at') ? new Date(value(data, 'submitted_at')).toISOString() : null, channel: optional(data, 'channel'), receipt_ref: optional(data, 'receipt_ref') }); changed(); }, 'Evento registrado.'); }}><Field label="Novo estado"><select value={target} onChange={(event) => setTarget(event.target.value)}>{transitions[item.status]?.map((state) => <option key={state} value={state}>{labels[state]}</option>)}</select></Field><Field label="Nota sobre a atualização"><textarea name="note" maxLength={3000} rows={2} /></Field>{target === 'SUBMITTED' && <fieldset><legend>Registro de envio manual</legend><Field label="Data e hora do envio"><input type="datetime-local" name="submitted_at" required /></Field><Field label="Canal utilizado"><input name="channel" required placeholder="Ex.: portal da empresa" /></Field><Field label="Referência do comprovante"><input name="receipt_ref" required placeholder="Ex.: confirmação recebida / número do processo" /></Field><label className="check"><input type="checkbox" name="manual_confirmation" required />Confirmo que eu já enviei esta candidatura fora da aplicação.</label></fieldset>}{task.feedback}<button className="primary" disabled={task.busy}>Salvar atualização</button></form></details>}
  </article>;
}
